"""스마트폰 자산 베이커 (오프라인 prep 스크립트 — 앱에서 import하지 않음).

ProcTHOR/AI2-THOR Cellphone STL을 내려받아 1레벨 미드포인트 세분화 후 정규화하고,
두께축 기준으로 액정/후면 케이스/측면 프레임으로 분할해 단일 geometry-only
OBJ(smartphone.obj)와 부품 sidecar(smartphone.components.json)를 생성한다.

출처/라이선스: MIT — zhiyuan-gao/unity_prefab_converter (AI2-THOR/ProcTHOR 파생)
  https://github.com/zhiyuan-gao/unity_prefab_converter (LICENSE: MIT)
  커밋 고정: 2b25e167da909c52bd3982679c69893d20372fa0
  원본 파일: procthor_assets/Cellphone_8/MeshCellphone_4_0.stl

인덱스 일관성(prep_hubble.py와 동일 계약): OBJ v-라인 순서 = 세분화 후 정점
순서. meshio는 그 순서로 points를 쌓으므로 components.json의 vertex_indices는
FE/BE 어느 쪽 파싱에서도 같은 정점을 가리킨다. 그룹 마커(o/g)는 쓰지 않는다.

세분화: 삼각형 4-분할(midpoint) 1레벨 — 각 edge 중점을 새 정점으로, 삼각형
하나를 4개로. 원본 STL은 1119 정점/1694 삼각형(watertight)이라 3929/6776이 된다.

분할: 두께축(bbox 최소 extent 축) 정규화 좌표 t로 액정 t>0.75 / 후면 t<0.25 /
측면 프레임 나머지. FRONT_IS_POSITIVE_Z=True 가정 — 최초 1회 시각 확인 권장.

사용법:
  python prep_smartphone.py            # 다운로드 → ./smartphone.obj + .components.json
  python prep_smartphone.py --src-dir <dir>   # 이미 받아둔 STL 디렉토리 재사용
"""

from __future__ import annotations

import argparse
import json
import os
import tempfile
import urllib.request

import meshio
import numpy as np

COMMIT = "2b25e167da909c52bd3982679c69893d20372fa0"
SRC_FILE = "MeshCellphone_4_0.stl"
URL = (
    "https://raw.githubusercontent.com/zhiyuan-gao/unity_prefab_converter/"
    f"{COMMIT}/procthor_assets/Cellphone_8/{SRC_FILE}"
)

NORMALIZED_DIAG = 2.0  # 정규화 목표 bbox 대각선 (내장 plate/can·허블과 동일 스케일)
# 실물 환산: ProcTHOR 자산은 meter-scale, 원본 대각선 ≈ 0.166 m → 6.9 배 아닌
# 자체 스케일. NORMALIZED_DIAG로 나눈 값을 real_scale로 bake (prep 실행 시 계산).
FRONT_IS_POSITIVE_Z = True  # 액정면이 +z (최초 1회 시각 확인)
SCREEN_T = 0.75   # 두께 정규화 t > 이 값 = 액정
BACK_T = 0.25     # t < 이 값 = 후면 케이스

# 낙하 기본: 화면면이 바닥을 향하도록 (액정 파손 시나리오).
DEFAULT_DROP_HEIGHT = 1.0
SCREEN_DOWN_EULER = [180.0, 0.0, 0.0] if FRONT_IS_POSITIVE_Z else [0.0, 0.0, 0.0]


def fetch_stl(src_dir: str | None, dst_dir: str) -> str:
    if src_dir:
        path = os.path.join(src_dir, SRC_FILE)
        if not os.path.isfile(path):
            # 스크래치 캐시는 다른 이름(cellphone8.stl)으로 받았을 수 있다.
            alt = os.path.join(src_dir, "cellphone8.stl")
            if os.path.isfile(alt):
                return alt
            raise FileNotFoundError(f"--src-dir에 {SRC_FILE!r} 없음: {path}")
        return path
    path = os.path.join(dst_dir, SRC_FILE)
    print(f"downloading {URL}")
    urllib.request.urlretrieve(URL, path)
    return path


def subdivide(points: np.ndarray, tris: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """삼각형 4-분할 (midpoint) 1레벨. (N,3)+(M,3) → (N+E,3)+(4M,3)."""
    edges = np.sort(
        np.concatenate([tris[:, [0, 1]], tris[:, [1, 2]], tris[:, [2, 0]]]), axis=1
    )
    uniq, inv = np.unique(edges, axis=0, return_inverse=True)
    mids = (points[uniq[:, 0]] + points[uniq[:, 1]]) / 2.0
    new_points = np.concatenate([points, mids], axis=0)
    m = len(tris)
    m01 = len(points) + inv[:m]
    m12 = len(points) + inv[m:2 * m]
    m20 = len(points) + inv[2 * m:3 * m]
    a, b, c = tris[:, 0], tris[:, 1], tris[:, 2]
    new_tris = np.concatenate([
        np.stack([a, m01, m20], axis=1),
        np.stack([b, m12, m01], axis=1),
        np.stack([c, m20, m12], axis=1),
        np.stack([m01, m12, m20], axis=1),
    ], axis=0)
    return new_points, new_tris


def write_obj(path: str, points: np.ndarray, faces: np.ndarray, segments) -> None:
    """geometry-only OBJ 기록 (prep_hubble.py write_obj와 동일 규약)."""
    with open(path, "w", encoding="ascii", newline="\n") as f:
        f.write("# Smartphone - ProcTHOR/AI2-THOR Cellphone_8 (MIT license)\n")
        f.write(f"# source: {URL} (commit {COMMIT})\n")
        f.write("# generated by prep_smartphone.py - DO NOT edit by hand; re-bake instead.\n")
        f.write("# normalized: centered at origin, bbox diagonal = 2.0; 1x midpoint subdivision\n")
        for sid, count in segments:
            f.write(f"# segment: {sid} ({count} vertices)\n")
        for x, y, z in points.tolist():
            f.write(f"v {x!r} {y!r} {z!r}\n")
        for a, b, c in faces + 1:  # OBJ는 1-based
            f.write(f"f {a} {b} {c}\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--src-dir", default=None, help="이미 받아둔 STL 디렉토리")
    args = parser.parse_args()
    out_dir = os.path.dirname(os.path.abspath(__file__))

    with tempfile.TemporaryDirectory() as tmp:
        stl_path = fetch_stl(args.src_dir, tmp)
        mesh = meshio.read(stl_path)
    points = np.asarray(mesh.points, dtype=np.float64)
    tris = np.concatenate(
        [np.asarray(c.data, dtype=np.int64) for c in mesh.cells if c.type == "triangle"]
    )
    print(f"  원본: {len(points)} verts, {len(tris)} tris")

    points, faces = subdivide(points, tris)
    assert len(points) == 3929 and len(faces) == 6776, \
        f"세분화 결과 예상과 다름: {len(points)}/{len(faces)}"

    # 정규화: 중심 원점, bbox 대각선 2.0.
    lo, hi = points.min(0), points.max(0)
    raw_diag = float(np.linalg.norm(hi - lo))
    points = (points - (lo + hi) / 2.0) * (NORMALIZED_DIAG / raw_diag)
    real_scale = raw_diag / NORMALIZED_DIAG  # m/unit (원본이 meter-scale)

    # 두께축 분할.
    lo, hi = points.min(0), points.max(0)
    thick_axis = int(np.argmin(hi - lo))
    t = (points[:, thick_axis] - lo[thick_axis]) / (hi[thick_axis] - lo[thick_axis])
    if not FRONT_IS_POSITIVE_Z:
        t = 1.0 - t
    screen = np.nonzero(t > SCREEN_T)[0]
    back = np.nonzero(t < BACK_T)[0]
    frame = np.nonzero((t >= BACK_T) & (t <= SCREEN_T))[0]
    assert len(screen) + len(back) + len(frame) == len(points), "분할 누락"
    assert len(screen) and len(back) and len(frame), "빈 분할 존재"
    print(f"  분할: 액정 {len(screen)} / 후면 {len(back)} / 프레임 {len(frame)}")

    obj_path = os.path.join(out_dir, "smartphone.obj")
    write_obj(obj_path, points, faces,
              [("screen", len(screen)), ("back_case", len(back)), ("side_frame", len(frame))])

    # 재파싱 검증.
    reread = meshio.read(obj_path)
    re_tris = np.concatenate(
        [np.asarray(c.data, dtype=np.int64) for c in reread.cells if c.type == "triangle"]
    )
    assert reread.points.shape == points.shape and np.array_equal(re_tris, faces)
    assert np.allclose(reread.points, points, rtol=0, atol=0), "재파싱 좌표 불일치"

    # 기본 충격점: 액정 무게중심에서 가장 가까운 액정 정점.
    sc_pts = points[screen]
    sc_center = sc_pts.mean(0)
    default_impact = int(screen[np.argmin(np.linalg.norm(sc_pts - sc_center, axis=1))])

    diag2 = NORMALIZED_DIAG  # 임계값 계산 기준
    components = [
        {
            "id": "screen", "name": "액정", "material": "강화 커버글라스",
            "fragility": "high", "notes": "낙하 충격에 균열이 쉽게 발생 — 임계값 최저.",
            "damage_threshold": round(0.012 * diag2, 6), "warn_ratio": 0.7,
            "yield_strain": 0.002,  # 취성 유리
            "functional": {"type": "screen"},
            "vertex_indices": [int(i) for i in screen],
        },
        {
            "id": "back_case", "name": "후면 케이스", "material": "알루미늄/글라스 백",
            "fragility": "medium", "notes": "찍힘/변형은 있으나 액정보다 튼튼.",
            "damage_threshold": round(0.025 * diag2, 6), "warn_ratio": 0.7,
            "yield_strain": 0.004,
            "vertex_indices": [int(i) for i in back],
        },
        {
            "id": "side_frame", "name": "측면 프레임", "material": "금속 프레임",
            "fragility": "low", "notes": "구조 강성이 높은 테두리 — 임계값 최고.",
            "damage_threshold": round(0.035 * diag2, 6), "warn_ratio": 0.7,
            "yield_strain": 0.004,
            "vertex_indices": [int(i) for i in frame],
        },
    ]
    doc = {
        "schema_version": 1,
        "asset": "smartphone.obj",
        "display_name": "스마트폰",
        "source": f"{URL} (commit {COMMIT}, MIT)",
        "normalized": f"centered at origin, bbox diagonal = {NORMALIZED_DIAG}, 1x subdivision",
        "real_scale_m_per_unit": round(real_scale, 6),
        "default_impact_node": default_impact,
        "default_radius": 0.12,
        "default_drop_height": DEFAULT_DROP_HEIGHT,
        "default_drop_orientation": "화면면 아래",
        "drop_orientations": [{"name": "화면면 아래", "euler_deg": SCREEN_DOWN_EULER}],
        "components": components,
    }
    json_path = os.path.join(out_dir, "smartphone.components.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"wrote {obj_path}: {len(points)} verts, {len(faces)} tris (verified round-trip)")
    print(f"wrote {json_path}: 3 components, default_impact_node={default_impact}, "
          f"real_scale={real_scale:.4g} m/unit")


if __name__ == "__main__":
    main()
